# eureka:
#   client:
#     instance:
#       serverUrl:
#         defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: admin
    url: jdbc:postgresql://localhost:5432/microservice-end-to-end
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
